### ISSUE TITLE
DiscordRESTError [404]: Unknown interaction

### ISSUE THREAD

**Issue by FilipeAleixo** [Snazzah/slash-create#334]
The same bot that's working locally with `slash-create` on Windows 11 doesn't work on Ubuntu.

On Ubuntu I always get this error, doesn't matter the command.

![image](https://user-images.githubusercontent.com/12476396/178103594-729ccff0-528f-46ce-965d-f934dd009789.png)

Versions (using the same versions both on Ubuntu and Windows):
nodejs: 16.14.2
npm: 8.12.2
slash-create: 5.0.3
discord.js: 13.6.0

Tried updating slash-create to latest, still have the same problem on Ubuntu.

Here's the entry point file:

```
import * as Sentry from '@sentry/node';
import {
	SlashCreator,
	GatewayServer,
	SlashCommand,
	CommandContext,
} from 'slash-create';
import Discord, {
	Client,
	ClientOptions,
	Intents,
	WSEventType,
} from 'discord.js';
import path from 'path';
import fs from 'fs';
import Log, { LogUtils } from './utils/Log';
import apiKeys from './service/constants/apiKeys';
import constants from './service/constants/constants';
import { RewriteFrames } from '@sentry/integrations';

initializeSentryIO();
const client: Client = initializeClient();
initializeEvents();

const creator = new SlashCreator({
	applicationID: process.env.DISCORD_BOT_APPLICATION_ID,
	publicKey: process.env.DISCORD_BOT_PUBLIC_KEY,
	token: process.env.DISCORD_BOT_TOKEN,
});

creator.on('debug', (message) => Log.debug(`debug: ${ message }`));
creator.on('warn', (message) => Log.warn(`warn: ${ message }`));
creator.on('error', (error: Error) => Log.error(`error: ${ error }`));
creator.on('synced', () => Log.debug('Commands synced!'));
creator.on('commandRegister', (command: SlashCommand) => Log.debug(`Registered command ${command.commandName}`));
creator.on('commandError', (command: SlashCommand, error: Error) => Log.error(`Command ${command.commandName}:`, {
	indexMeta: true,
	meta: {
		name: error.name,
		message: error.message,
		stack: error.stack,
		command,
	},
}));

// Ran after the command has completed
creator.on('commandRun', (command:SlashCommand, result: Promise<any>, ctx: CommandContext) => {
	LogUtils.logCommandEnd(ctx);
});

// Register command handlers
creator
	.withServer(
		new GatewayServer((handler) => client.ws.on(<WSEventType>'INTERACTION_CREATE', handler)),
	)
	.registerCommandsIn(path.join(__dirname, 'commands'))
	.syncCommands();

// Log client errors
client.on('error', Log.error);

client.login(process.env.DISCORD_BOT_TOKEN);

function initializeClient(): Client {
	const clientOptions: ClientOptions = {
		intents: [
			Intents.FLAGS.GUILDS,
			Intents.FLAGS.GUILD_BANS,
			Intents.FLAGS.GUILD_MEMBERS,
			Intents.FLAGS.GUILD_EMOJIS_AND_STICKERS,
			Intents.FLAGS.GUILD_VOICE_STATES,
			Intents.FLAGS.GUILD_PRESENCES,
			Intents.FLAGS.GUILD_MESSAGES,
			Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
			Intents.FLAGS.DIRECT_MESSAGES,
			Intents.FLAGS.DIRECT_MESSAGE_REACTIONS,
		],
		partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'USER'],
	};
	return new Discord.Client(clientOptions);
}

function initializeEvents(): void {
	const eventFiles = fs.readdirSync(path.join(__dirname, '/events')).filter(file => file.endsWith('.js'));
	eventFiles.forEach(file => {
		const event = new (require(`./events/${file}`).default)();
		try {
			if (event.once) {
				client.once(event.name, (...args) => event.execute(...args, client));
			} else {
				client.on(event.name, (...args) => event.execute(...args, client));
			}
		} catch (e) {
			Log.error('Event failed to process', {
				indexMeta: true,
				meta: {
					name: e.name,
					message: e.message,
					stack: e.stack,
					event,
				},
			});
		}
	});
}

function initializeSentryIO() {
	Sentry.init({
		dsn: `${apiKeys.sentryDSN}`,
		tracesSampleRate: 1.0,
		debug: true,
		release: `${constants.APP_NAME}@${constants.APP_VERSION}`,
		environment: `${process.env.SENTRY_ENVIRONMENT}`,
		integrations: [
			new RewriteFrames({
				root: __dirname,
			}),
			new Sentry.Integrations.Http({ tracing: true }),
		],
	});
}

export default client;
```

Don't know how to debug this. Any ideas? Thanks!

**Comment by Snazzah** [comment]
Is this error consistent every time you use it? You could try and manually defer before doing anything.

**Comment by FilipeAleixo** [comment]
@Snazzah yes it happens everytime on Ubuntu, even if the command just returns a message. I saw this issue and tried manually deferring, but the problem remained  https://github.com/Snazzah/slash-create/issues/78

**Comment by Snazzah** [comment]
What's the logs you get when you run it locally? Seems like the callback took 4 seconds to do.

**Comment by FilipeAleixo** [comment]
Copying here the whole thing I get in the command line - this command was supposed to return a modal

```
> co-kong@1.0.0 start
> node --trace-warnings -r dotenv/config dist/app.js

Logger initialized!
Sentry Logger [log]: Integration installed: InboundFilters
Sentry Logger [log]: Integration installed: FunctionToString
Sentry Logger [log]: Integration installed: ContextLines
Sentry Logger [log]: Integration installed: Console
Sentry Logger [log]: Integration installed: OnUncaughtException
Sentry Logger [log]: Integration installed: OnUnhandledRejection
Sentry Logger [log]: Integration installed: LinkedErrors
Sentry Logger [log]: Integration installed: RewriteFrames
Sentry Logger [log]: Integration installed: Http
Registered command co
debug: Registered command 1:global:co.
Registered command help
debug: Registered command 1:global:help.
debug: undefined 1657399821595 /applications/:id/commands 200: 3819ms (831ms avg) | 1/1 left | Reset 1657399821595 (0ms left)
debug: Found command "help" (993825534838571019, type 1)
debug: Found command "co" (994566656070270996, type 1)
debug: Finished syncing commands
Commands synced!
Starting up the bot...
Bot is active for: 851552281249972254, The Garage
Bot is active for: 880146700524724255, dev
CO Kong is ready to Coordinape!
debug: Running command: co (994566656070270996, guild 851552281249972254)
/co ran flx#1384
/co ended flx#1384
debug: undefined 1657399831577 /interactions/995431768134013049/:token/callback 404: 3751ms (1156ms avg) | 1/1 left | Reset 1657399831577 (0ms left)
DiscordRESTError [404]: Unknown interaction
    at RequestHandler.request (/home/anon/git/CO-Kong/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at SlashCreatorAPI.interactionCallback (/home/anon/git/CO-Kong/node_modules/slash-create/lib/api.js:80:45)
    at CommandContext._respond (/home/anon/git/CO-Kong/node_modules/slash-create/lib/creator.js:687:28)
    at CommandContext.sendModal (/home/anon/git/CO-Kong/node_modules/slash-create/lib/structures/interfaces/modalSendableContext.js:38:20)
    at /home/anon/git/CO-Kong/dist/utils/ServiceSupport.js:138:23
    at Generator.next (<anonymous>)
    at /home/anon/git/CO-Kong/dist/utils/ServiceSupport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anon/git/CO-Kong/dist/utils/ServiceSupport.js:4:12)
    at Object.configurationAlerts (/home/anon/git/CO-Kong/dist/utils/ServiceSupport.js:136:35) {
  req: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      error: [Array],
      abort: [Function],
      socket: [Function (anonymous)],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 739,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'discord.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'discord.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 15000,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 154,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 14116,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 163,
        [Symbol(triggerId)]: 162
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 1298,
      [Symbol(kBytesWritten)]: 1249,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /api/v8/interactions/995431768134013049/aW50ZXJhY3Rpb246OTk1NDMxNzY4MTM0MDEzMDQ5OmpKU2RSZFVaZ1IwRU94dTdySVFxSE5oenZPazF0MkN6bTF4alZhVFhoVHJraHNUZ1JNeDFMbWFJUFpYY2FvZWpEakEyWGNaSU5raHdHMkZ0a1NHTTBweFlVdTg5VkJxWlNuaDk2ZUdPaWlWZXFFRFVZUTBmWkpIYlNxOUI3bHgz/callback HTTP/1.1\r\n' +
      'User-Agent: DiscordBot (https://github.com/Snazzah/slash-create, 5.4.1)\r\n' +
      'Accept-Encoding: gzip,deflate\r\n' +
      'X-RateLimit-Precision: millisecond\r\n' +
      'Content-Type: application/json\r\n' +
      'Host: discord.com\r\n' +
      'Connection: close\r\n' +
      'Content-Length: 739\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/v8/interactions/995431768134013049/aW50ZXJhY3Rpb246OTk1NDMxNzY4MTM0MDEzMDQ5OmpKU2RSZFVaZ1IwRU94dTdySVFxSE5oenZPazF0MkN6bTF4alZhVFhoVHJraHNUZ1JNeDFMbWFJUFpYY2FvZWpEakEyWGNaSU5raHdHMkZ0a1NHTTBweFlVdTg5VkJxWlNuaDk2ZUdPaWlWZXFFRFVZUTBmWkpIYlNxOUI3bHgz/callback',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 36,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'discord.com',
    protocol: 'https:',
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'user-agent': [Array],
      'accept-encoding': [Array],
      'x-ratelimit-precision': [Array],
      'content-type': [Array],
      host: [Array]
    }
  },
  res: <ref *2> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      end: [Function: responseOnEnd],
      aborted: [Function]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'discord.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'discord.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 15000,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 154,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 14116,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 163,
        [Symbol(triggerId)]: 162
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 1298,
      [Symbol(kBytesWritten)]: 1249,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Date',
      'Sat, 09 Jul 2022 20:50:31 GMT',
      'Content-Type',
      'application/json',
      'Transfer-Encoding',
      'chunked',
      'Connection',
      'close',
      'set-cookie',
      '__dcfduid=c5963454ffc811ec97559abd5b0b4f5c; Expires=Thu, 08-Jul-2027 20:50:31 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/',
      'set-cookie',
      '__sdcfduid=c5963454ffc811ec97559abd5b0b4f5c85c57c240c5a1e878db870c311fca9b42e58734c0eb1ab6b6748c8f839357a46; Expires=Thu, 08-Jul-2027 20:50:31 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/',
      'strict-transport-security',
      'max-age=31536000; includeSubDomains; preload',
      'x-envoy-upstream-service-time',
      '16',
      'Via',
      '1.1 google',
      'Alt-Svc',
      'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
      'CF-Cache-Status',
      'DYNAMIC',
      'Expect-CT',
      'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'Report-To',
      '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=f7EUTQiTIPQzU5yEyqPuqHdeyeyfXFYE5PIybzvgUWS94yCMPzAmjnp9tV7EUoqHPL%2BaYkR9rJE%2B1etuI8ie5w6keu1%2FhocaWoou194k18SjbjqzUtDTs2rTpF0j"}],"group":"cf-nel","max_age":604800}',
      'NEL',
      '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      'X-Content-Type-Options',
      'nosniff',
      'Server',
      'cloudflare',
      'CF-RAY',
      '7283eeb27bd86617-MAD',
      'Content-Encoding',
      'gzip'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 404,
    statusMessage: 'Not Found',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'discord.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'discord.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 15000,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 154,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 14116,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 163,
        [Symbol(triggerId)]: 162
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 1298,
      [Symbol(kBytesWritten)]: 1249,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: true,
    _dumped: false,
    req: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 739,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /api/v8/interactions/995431768134013049/aW50ZXJhY3Rpb246OTk1NDMxNzY4MTM0MDEzMDQ5OmpKU2RSZFVaZ1IwRU94dTdySVFxSE5oenZPazF0MkN6bTF4alZhVFhoVHJraHNUZ1JNeDFMbWFJUFpYY2FvZWpEakEyWGNaSU5raHdHMkZ0a1NHTTBweFlVdTg5VkJxWlNuaDk2ZUdPaWlWZXFFRFVZUTBmWkpIYlNxOUI3bHgz/callback HTTP/1.1\r\n' +
        'User-Agent: DiscordBot (https://github.com/Snazzah/slash-create, 5.4.1)\r\n' +
        'Accept-Encoding: gzip,deflate\r\n' +
        'X-RateLimit-Precision: millisecond\r\n' +
        'Content-Type: application/json\r\n' +
        'Host: discord.com\r\n' +
        'Connection: close\r\n' +
        'Content-Length: 739\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v8/interactions/995431768134013049/aW50ZXJhY3Rpb246OTk1NDMxNzY4MTM0MDEzMDQ5OmpKU2RSZFVaZ1IwRU94dTdySVFxSE5oenZPazF0MkN6bTF4alZhVFhoVHJraHNUZ1JNeDFMbWFJUFpYY2FvZWpEakEyWGNaSU5raHdHMkZ0a1NHTTBweFlVdTg5VkJxWlNuaDk2ZUdPaWlWZXFFRFVZUTBmWkpIYlNxOUI3bHgz/callback',
      _ended: true,
      res: [Circular *2],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'discord.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      date: 'Sat, 09 Jul 2022 20:50:31 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'set-cookie': [Array],
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'x-envoy-upstream-service-time': '16',
      via: '1.1 google',
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
      'cf-cache-status': 'DYNAMIC',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=f7EUTQiTIPQzU5yEyqPuqHdeyeyfXFYE5PIybzvgUWS94yCMPzAmjnp9tV7EUoqHPL%2BaYkR9rJE%2B1etuI8ie5w6keu1%2FhocaWoou194k18SjbjqzUtDTs2rTpF0j"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      'x-content-type-options': 'nosniff',
      server: 'cloudflare',
      'cf-ray': '7283eeb27bd86617-MAD',
      'content-encoding': 'gzip'
    },
    [Symbol(kHeadersCount)]: 36,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  },
  response: { message: 'Unknown interaction', code: 10062 },
  code: 404
}

```

**Comment by FilipeAleixo** [comment]
This might be related. Error code is also 10062 https://github.com/EQUENOS/dislash.py/issues/1

**Comment by Snazzah** [comment]
I think the problem is that your latency is way too high, syncing commands took `3819ms` amd trying to callback to discord took `3751ms`. Can't repro this so this might be an issue with your connection.
