### ISSUE TITLE
DiscordRESTError [404]: Unknown interaction

### ISSUE THREAD

**Issue by karelianpie** [Snazzah/slash-create#438]
When calling
```typescript
await componentContext.editParent({ components: [] });
```
I am getting this error
```
DiscordRESTError [404]: Unknown interaction
    at RequestHandler.request (root/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at SlashCreatorAPI.interactionCallback (root/node_modules/slash-create/lib/api.js:84:45)
    at ComponentContext._respond (root/node_modules/slash-create/lib/creator.js:695:28)
    at ComponentContext.acknowledge (root/node_modules/slash-create/lib/structures/interfaces/componentContext.js:35:24)
    at Timeout.<anonymous> (root/node_modules/slash-create/lib/structures/interfaces/componentContext.js:25:51)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Am I missing something?

**Comment by karelianpie** [comment]
Unrelated to slash create
