### ISSUE TITLE
Interactions failing with 404 sometimes

### ISSUE THREAD

**Issue by Techbot121** [Snazzah/slash-create#78]
I've been noticing some strange behaviour on our bot we're using with slash-create.

After initially launching the bot the commands would work fine, but if it has been running for a couple minutes all interactions would fail with the code `10062` unless I add a ```await ctx.defer()``` in front of every command.

More importantly if I use the new MessageComponents the interaction will also fail after 2-3 minutes or so after not interacting with it, even though the interaction is supposed to last up to 15 minutes.

I'm not sure if it's just a timing issue, intended or if it's actually a bug.

here is the full stack of the error that occurs (for the gserv command in this case):
```
(node:3523014) UnhandledPromiseRejectionWarning: DiscordRESTError [404]: Unknown interaction
Error: 
    at RequestHandler.request (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at SlashCreatorAPI.interactionCallback (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/api.js:79:45)
    at ComponentContext._respond (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/creator.js:585:28)
    at ComponentContext.acknowledge (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/structures/interfaces/componentContext.js:35:24)
    at Timeout.<anonymous> (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/structures/interfaces/componentContext.js:24:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

The code for the bot is public and the commands are located here:
https://github.com/Metastruct/node-metaconcord/tree/master/app/services/discord/commands

**Comment by Snazzah** [comment]
Might be some sort of timing issue with using `setTimeout` to auto-defer. The reason that all interactions would fail without deferring is that there needs to be an initial response for the interaction to be valid. This should already be solved since a timeout is created when a command context is made. The components are even weirder since they are just reading off of `Date.now()` and checking to see if its been 15 minutes. Is there anything messing with dates internally?

**Comment by Techbot121** [comment]
I've done some testing and came to the conclusion that this only happens if you call a longer running synchronous function via ctx.send or just returning in the run function.

**Comment by Snazzah** [comment]
That's odd. Seems like a timing issue, since the error is coming from the timeout of the component context. You shouldn't need to manually defer.

**Comment by Techbot121** [comment]
did some more testing, here is what I used to test:

```ts
async run(): Promise<any> {
	const is = Date.now();
	console.log(is);
	while (Date.now() - is < 5000) {}
	return "a";
}
```

this always fails for me, I printed the time on each step and it delays here 
https://github.com/Snazzah/slash-create/blob/master/src/creator.ts#L781

I also added some extra printing to the defer function 
https://github.com/Snazzah/slash-create/blob/master/src/structures/interfaces/messageInteraction.ts#L274
and it's not being run at all, as if the timeout never happens, unless I manually defer before explicitly.

maybe using something like `Promise.race` in _runCommand could work?

hope this helps.

**Comment by Snazzah** [comment]
Try debugging from here:
- https://github.com/Snazzah/slash-create/blob/master/src/structures/interfaces/context.ts#L91

This is where the timeout should be created for command contexts.

**Comment by Techbot121** [comment]
I already did this yesterday, the function does exist and all but it doesn't seem run while the promise is being awaited.

```
>>> setting this._setTimeout func in context 1626971022839
>>> ctx created, timeout func: Timeout {
  _idleTimeout: 2000,
  _idlePrev: [TimersList],
  _idleNext: [TimersList],
  _idleStart: 8828,
  _onTimeout: [Function],
  _timerArgs: undefined,
  _repeat: null,
  _destroyed: false,
  [Symbol(refed)]: true,
  [Symbol(asyncId)]: 993,
  [Symbol(triggerId)]: 119
} 1626971022839
>>> Command run() in SlashCommand 1626971022840
>>> pre await promise _runCommand 1626971027840
(node:2102474) UnhandledPromiseRejectionWarning: DiscordRESTError [404]: Unknown interaction
Error: 
    at RequestHandler.request (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at SlashCreatorAPI.interactionCallback (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/api.js:79:45)
    at CommandContext._respond (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/creator.js:588:28)
    at CommandContext.send (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:79:24)
    at SlashTestCommand.finalize (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/command.js:164:24)
    at SlashCreator._runCommand (/home/metaconcord/node-metaconcord/node_modules/slash-create/lib/creator.js:573:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Snazzah** [comment]
Weird bug, but it is at least fixable with manual deferring. Not sure how to restructure to avoid this, but in most cases this won't be an issue. Thanks for being in-depth with this though.
